name: SFDL

on: push

jobs:
    build-sfdl:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: build toolchain container
              run: docker build . -t builder
            - name: build sfdl
              run: |
                docker build . -t builder
                docker run --rm -v ${PWD}:/project builder make
            - name: build wuhb
              run: docker run --rm -v ${PWD}:/project builder wuhbtool --name=SplatfestDLPP --short-name=aromaSFDL --author=andrea --icon=sfs.png --tv-image=tv.png --drc-image=sillydrc.png SplatfestDL_Plus.rpx SFDL.wuhb
            - uses: actions/upload-artifact@master
              with:
                  name: sfdl-elf
                  path: "*.elf"
            - uses: actions/upload-artifact@master
              with:
                  name: sfdl-rpx
                  path: "*.rpx"
            - uses: actions/upload-artifact@master
              with:
                  name: sfdl-wuhb
                  path: "*.wuhb"
